CREATE NODE TABLE IF NOT EXISTS Episode(id STRING, ts STRING, PRIMARY KEY(id));
CREATE NODE TABLE IF NOT EXISTS Entity(id STRING, name STRING, PRIMARY KEY(id));
CREATE NODE TABLE IF NOT EXISTS Skill(id STRING, name STRING, usage_count INT64, PRIMARY KEY(id));
CREATE NODE TABLE IF NOT EXISTS AffinityState(id STRING, score DOUBLE, PRIMARY KEY(id));
CREATE REL TABLE IF NOT EXISTS FOLLOWS(FROM Episode TO Episode);
CREATE REL TABLE IF NOT EXISTS REFERENCES(FROM Episode TO Entity);
CREATE REL TABLE IF NOT EXISTS FRUSTRATED_BY(FROM AffinityState TO Episode);
CREATE REL TABLE IF NOT EXISTS CONFIRMS(FROM AffinityState TO Episode);
